client:
 build: ./docker
 dockerfile: dev-Dockerfile
 links:
  - server
 volumes:
  - $PWD:/home/dogfish/src
 command: ash -c "cd /home/dogfish/src && npm install --dev && npm install seneca${SENECA_VER} && nodemon -L --ignore 'test/*.js' ./test/test-client.js"

server:
 build: ./docker
 dockerfile: dev-Dockerfile
 links:
  - neo4j
 volumes:
  - $PWD:/home/dogfish/src
 command: ash -c "cd /home/dogfish/src && npm install --dev && npm install seneca${SENECA_VER} && nodemon -L --ignore 'test/*.js' ./user-service.js"

test:
 build: ./docker
 links:
  - neo4j
 user: dogfish
 command: ash -c "cd /home/dogfish/src && npm install --dev && npm install seneca${SENECA_VER} && npm test"

neo4j:
 build: ./docker
 dockerfile: neo4j-Dockerfile
 ports: 
  - "7474:7474"
  - "7473:7473"
  - "7687:7687"
 environment:
  - NEO4J_AUTH=neo4j/u535s3rv1c3
