test:
 build: .
 links:
  - user
 volumes:
  - $PWD/..:/home/dogfish/src
 command: ash -c "cd /home/dogfish/src && npm install --dev && npm install seneca${SENECA_VER} && npm test"

user-dev:
 build: .
 dockerfile: dev-Dockerfile
 links:
  - neo4j
 volumes:
  - $PWD/..:/home/dogfish/src
 command: ash -c "cd /home/dogfish/src && npm install --dev && npm install seneca${SENECA_VER} && nodemon -L --ignore 'test/*.js' ./user-service.js"

user:
 build: .
 links:
  - neo4j
 volumes:
  - $PWD/..:/home/dogfish/src
 command: ash -c "cd /home/dogfish/src && npm install --dev && npm install seneca${SENECA_VER} && node ./user-service.js"

neo4j:
 build: .
 dockerfile: neo4j-Dockerfile
 ports: 
  - "7474:7474"
  - "7473:7473"
  - "7687:7687"
 environment:
  - NEO4J_AUTH=neo4j/u535s3rv1c3
